// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alexrodfe/golang-challenge-1.2.0/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoriesRepository creates a new instance of CategoriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoriesRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CategoriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CategoriesRepository is an autogenerated mock type for the CategoriesRepository type
type CategoriesRepository struct {
	mock.Mock
}

type CategoriesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoriesRepository) EXPECT() *CategoriesRepository_Expecter {
	return &CategoriesRepository_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type CategoriesRepository
func (_mock *CategoriesRepository) CreateCategory(category models.ProductCategory) (*models.ProductCategory, error) {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *models.ProductCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.ProductCategory) (*models.ProductCategory, error)); ok {
		return returnFunc(category)
	}
	if returnFunc, ok := ret.Get(0).(func(models.ProductCategory) *models.ProductCategory); ok {
		r0 = returnFunc(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.ProductCategory) error); ok {
		r1 = returnFunc(category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoriesRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type CategoriesRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - category models.ProductCategory
func (_e *CategoriesRepository_Expecter) CreateCategory(category any) *CategoriesRepository_CreateCategory_Call {
	return &CategoriesRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", category)}
}

func (_c *CategoriesRepository_CreateCategory_Call) Run(run func(category models.ProductCategory)) *CategoriesRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ProductCategory
		if args[0] != nil {
			arg0 = args[0].(models.ProductCategory)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CategoriesRepository_CreateCategory_Call) Return(productCategory *models.ProductCategory, err error) *CategoriesRepository_CreateCategory_Call {
	_c.Call.Return(productCategory, err)
	return _c
}

func (_c *CategoriesRepository_CreateCategory_Call) RunAndReturn(run func(category models.ProductCategory) (*models.ProductCategory, error)) *CategoriesRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function for the type CategoriesRepository
func (_mock *CategoriesRepository) GetAllCategories() ([]models.ProductCategory, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []models.ProductCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.ProductCategory, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.ProductCategory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoriesRepository_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type CategoriesRepository_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
func (_e *CategoriesRepository_Expecter) GetAllCategories() *CategoriesRepository_GetAllCategories_Call {
	return &CategoriesRepository_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories")}
}

func (_c *CategoriesRepository_GetAllCategories_Call) Run(run func()) *CategoriesRepository_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CategoriesRepository_GetAllCategories_Call) Return(productCategorys []models.ProductCategory, err error) *CategoriesRepository_GetAllCategories_Call {
	_c.Call.Return(productCategorys, err)
	return _c
}

func (_c *CategoriesRepository_GetAllCategories_Call) RunAndReturn(run func() ([]models.ProductCategory, error)) *CategoriesRepository_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}
