// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mytheresa/go-hiring-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// NewProductsRepository creates a new instance of ProductsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ProductsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ProductsRepository is an autogenerated mock type for the ProductsRepository type
type ProductsRepository struct {
	mock.Mock
}

type ProductsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductsRepository) EXPECT() *ProductsRepository_Expecter {
	return &ProductsRepository_Expecter{mock: &_m.Mock}
}

// GetAllProducts provides a mock function for the type ProductsRepository
func (_mock *ProductsRepository) GetAllProducts(offset int, limit int, filters models.ProductFilters) ([]models.Product, int64, error) {
	ret := _mock.Called(offset, limit, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int, models.ProductFilters) ([]models.Product, int64, error)); ok {
		return returnFunc(offset, limit, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, models.ProductFilters) []models.Product); ok {
		r0 = returnFunc(offset, limit, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, models.ProductFilters) int64); ok {
		r1 = returnFunc(offset, limit, filters)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int, models.ProductFilters) error); ok {
		r2 = returnFunc(offset, limit, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ProductsRepository_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type ProductsRepository_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - offset int
//   - limit int
//   - filters models.ProductFilters
func (_e *ProductsRepository_Expecter) GetAllProducts(offset any, limit any, filters any) *ProductsRepository_GetAllProducts_Call {
	return &ProductsRepository_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", offset, limit, filters)}
}

func (_c *ProductsRepository_GetAllProducts_Call) Run(run func(offset int, limit int, filters models.ProductFilters)) *ProductsRepository_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.ProductFilters
		if args[2] != nil {
			arg2 = args[2].(models.ProductFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductsRepository_GetAllProducts_Call) Return(products []models.Product, n int64, err error) *ProductsRepository_GetAllProducts_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *ProductsRepository_GetAllProducts_Call) RunAndReturn(run func(offset int, limit int, filters models.ProductFilters) ([]models.Product, int64, error)) *ProductsRepository_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByCode provides a mock function for the type ProductsRepository
func (_mock *ProductsRepository) GetProductByCode(code string) (*models.Product, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByCode")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Product, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Product); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductsRepository_GetProductByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByCode'
type ProductsRepository_GetProductByCode_Call struct {
	*mock.Call
}

// GetProductByCode is a helper method to define mock.On call
//   - code string
func (_e *ProductsRepository_Expecter) GetProductByCode(code any) *ProductsRepository_GetProductByCode_Call {
	return &ProductsRepository_GetProductByCode_Call{Call: _e.mock.On("GetProductByCode", code)}
}

func (_c *ProductsRepository_GetProductByCode_Call) Run(run func(code string)) *ProductsRepository_GetProductByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProductsRepository_GetProductByCode_Call) Return(product *models.Product, err error) *ProductsRepository_GetProductByCode_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductsRepository_GetProductByCode_Call) RunAndReturn(run func(code string) (*models.Product, error)) *ProductsRepository_GetProductByCode_Call {
	_c.Call.Return(run)
	return _c
}
